### ISSUE TITLE
Claiming a Guild only shows on the bedrock 

### ISSUE THREAD

**Issue by iProCraft** [guilds-plugin/Guilds#604] opened 2022-08-11 04:39 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Guilds 3.5.6.4
* MC Version 1.18.2
* Plugin List

**Comment by wolfebersahd** [comment] 2022-09-15 12:16
There are not steps to reproduce and I can't reproduce this.

Please provide more information, including server type, Spigot/PaperMc, etc. And WorldEdit/worldguard versions.

**Comment by darbyjack** [comment] 2022-12-23 04:40
Fixed via https://github.com/guilds-plugin/Guilds/commit/f39f01c3b79b4a5ad49001b08872f95340017ddc

**Closed by darbyjack** 2022-12-23 04:40 UTC
