### ISSUE TITLE
bukkit permissions to specific roles?

### ISSUE THREAD

**Issue by MajorBarnulf** [guilds-plugin/Guilds#309] opened 2020-04-16 20:59 UTC
## Context
With friends of mine, we're setting up a semi-RP 1.15.2 server, we already have some player making their guilds, but their villages/bases are far away from the spawn, so we made some parcels at the spawn (with the "area shop" plugin) and we want each guild to be able to buy their own parcel, but we wan't them to be able to buy only one of them per guilds, so we would like to give a certain permission from "area shop" to the chief of each guild but not to all of their others members.

## Possible Implementation
We would like a place in the configuration file of the roles to give bukkit permissions to specific roles

**Comment by darbyjack** [comment] 2020-04-16 21:14
Duplicate of https://github.com/guilds-plugin/Guilds/issues/243

**Closed by darbyjack** 2020-04-16 21:14 UTC
