### ISSUE TITLE
IMPORTANT Feature Request: Multiplie claims

### ISSUE THREAD

**Issue by Golicraft** [guilds-plugin/Guilds#297] opened 2020-03-21 16:24 UTC
## Context

This is REALLY important because it let us give players smaller land at first claim and then they can claim more times to expand their land. It should cost money to claim and maybe receive some of the money back when you remove a claim. 

It is actually common sense. I do not understand why this plugin only had one claim per guild and if I had known it before I bought it I haven't. It doesn't fit how my server is built up and I hope this really can change. Look at other claiming plugins, they do not support only ONE CLAIM

## Possible Implementation

None

**Comment by wolfebersahd** [comment] 2020-03-21 17:05
This is a duplicate of #172 

There has been a lot of talk about a new claim system. But it's not currently a priority.

**Closed** 2020-03-21 21:46 UTC
