### ISSUE TITLE
Error while creating guild

### ISSUE THREAD

**Issue by wesley376** [guilds-plugin/Guilds#710] opened 2024-01-27 02:32 UTC
I get an error message in the console when I create a guild. However, everything seems to be working normally because the guild is created.

![Screenshot 2024-01-27 033118](https://github.com/guilds-plugin/Guilds/assets/52891579/06b3dde2-0c18-405b-ac71-657ea6e519e8)

**Comment by darbyjack** [comment] 2024-01-29 16:54
Duplicate of / related to https://github.com/guilds-plugin/Guilds/issues/707. Here is the solution for the time being:
![image](https://github.com/guilds-plugin/Guilds/assets/21014720/73c42e4a-73f4-4973-bf86-85233db58889)

**Closed by darbyjack** 2024-01-29 16:54 UTC

**Comment by w75896** [comment] 2024-02-08 13:13
this is not work still error.
![image](https://github.com/guilds-plugin/Guilds/assets/85177690/06c760f3-1ed2-4e64-b48d-10e5fa6a492b)
