### ISSUE TITLE
interact: false does do not allow eating

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#351] opened 2020-07-12 20:54 UTC
Players with a role with interact: false cannot eat in guild region.
Paper 1.16.1 b88 
Guild 3.5.3.3

**Comment by wolfebersahd** [comment] 2020-07-12 21:39
That's really stranger, This might be a WorldGuard issue since interact is a WorldGuard flag.

I don't have a test environment for 1.16.1 yet but if you can just make a WG region and add `/region flag <regionname> interact deny` and see if people can eat in the region.

**Comment by wolfebersahd** [comment] 2020-07-12 21:48
I can confirm i just checked it's a WorldGuard issues. The "interact" flag blocks interacting with all entities including food.

Also occurs on 1.15.2, it's not a Guilds issue.

**Comment by HauserGrim** [comment] 2020-07-13 10:52
Other people can eat with interact deny in the region.

**Comment by HauserGrim** [comment] 2020-07-14 07:40
![image](https://user-images.githubusercontent.com/37507220/87395398-f5b31f80-c5b9-11ea-9971-ed2c652cf338.png)


https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardPlayerListener.java
https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/EventAbstractionListener.java

**Comment by darbyjack** [comment] 2020-07-15 21:34
Good catch. Let me see if I can modify this to make it only work on blocks.

**Comment by darbyjack** [comment] 2020-07-15 21:37
I just pushed a new commit, can you try compiling and seeing if it fixed it?

**Comment by HauserGrim** [comment] 2020-07-16 14:58
You can eat and use items only if the player clicks through the air, items still cannot be used by clicking on blocks. Also, entities are not checked.

**Comment by HauserGrim** [comment] 2020-10-05 16:21
Maybe try event.useInteractedBlock() ?

**Comment by darbyjack** [comment] 2020-10-05 16:23
Was this not fixed? I could've sworn one of the commits I pushed fixed it.

**Comment by HauserGrim** [comment] 2020-10-05 17:53
https://github.com/guilds-plugin/Guilds/commit/ea3403e69947ae4350dbd4b6e3ae823dcebbbbf8
You still can't eat while looking at block.

**Comment by darbyjack** [comment] 2020-10-06 02:09
So you're saying if the `useInteractedBlock()` is null, return too to allow it?

**Comment by HauserGrim** [comment] 2020-10-06 11:06
Remove clickedBlock check.
if (event.useInteractedBlock() == Result.DENY) return; // If player not using block.
event.setUseInteractedBlock(Result.DENY); // To cancel interaction with block.

**Comment by darbyjack** [comment] 2020-10-06 16:13
So if I understand you properly, something like this? 
![image](https://user-images.githubusercontent.com/21014720/95228472-ff1ce400-07c4-11eb-80a9-07676f29baa4.png)

**Comment by HauserGrim** [comment] 2020-10-06 20:45
I am not good at Kotlin.
player.location gets player location? Isn't it more correct to get a block location?

isCancelled canceling event? I meant to use result.deny instead of canceling event.
Something like
![image](https://user-images.githubusercontent.com/37507220/95257291-c284d300-082c-11eb-872c-f39785eb8ec1.png)

**Comment by darbyjack** [comment] 2020-10-06 20:48
Ahh. Okay, I can try that. I'll shoot you a jar before I go to bed tonight or tomorrow. Are you in the Discord for this plugin so I can easily send a copy for you to test?

**Comment by HauserGrim** [comment] 2020-10-07 10:01
HauserGrim#7266

**Closed** 2020-10-08 17:21 UTC
