### ISSUE TITLE
Error on /guild list ,it wont appear

### ISSUE THREAD

**Issue by BroTegas** [guilds-plugin/Guilds#709] opened 2024-01-26 07:50 UTC
![error](https://github.com/guilds-plugin/Guilds/assets/157788674/6db974de-db37-4fbe-9f7d-75a9eeaa9b8d)

Gui for /guild list is not appear and its spam consule when we type the command.Other Gui works fine

**Comment by darbyjack** [comment] 2024-01-29 16:53
Duplicate of / related to https://github.com/guilds-plugin/Guilds/issues/707. Here is the solution for the time being:
![image](https://github.com/guilds-plugin/Guilds/assets/21014720/773a2fe5-a8ee-4522-a340-e0925ddbec6b)

**Closed by darbyjack** 2024-01-29 16:53 UTC

**Comment by BroTegas** [comment] 2024-03-11 03:00
i cant find the cross skull ,btw pls add me in the discord channel i i already wating for a month still the helpchat wont assign me to the guild channel

**Comment by darbyjack** [comment] 2024-03-11 03:12
> i cant find the cross skull ,btw pls add me in the discord channel i i already wating for a month still the helpchat wont assign me to the guild channel

What is your Discord name? You should be able to add yourself in the channel after you link your discord.
